version: '2'
services:
  moodle:
    image: docker.io/bitnami/moodle:4.1
    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_TYPE=mysqli
      - MOODLE_DATABASE_HOST=34.170.24.251
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=root
      - MOODLE_DATABASE_NAME=nfs
      - MOODLE_DATABASE_PASSWORD=123456789
    volumes:
      - /mnt/filedir/test3:/bitnami/moodle
      - 'moodledata_data:/bitnami/moodledata'
volumes:
  moodledata_data:
    driver: local